WebTechnology_Course/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^django-admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^login/$', views.login),
    url(r'^register/$', views.register),
    url(r'^logout/$', views.logout),
    url(r'^contact/$', views.contact),
    url(r'^error/[a-zA-Z0-9]+$', views.error),
    url(r'^author/[0-9]+$', views.author),
    url(r'^author/$', views.author),
    url(r'^genre/[0-9]+$', views.genre),
    url(r'^genre/$', views.genre),
    url(r'^book/[0-9]+$', views.book),
    url(r'^book/[0-9]+/chapter/[0-9]+/read$', views.read),
    url(r'^book/add$', views.add_book),
    url(r'^book/[0-9]+/addchapter$', views.add_chapter),
    url(r'^book/[0-9]+/chapter/[0-9]+/edit$', views.edit_chapter),
    url(r'^book/[0-9]+/vote/[0-9]+$', views.vote)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebTechnology_Course/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Book, BookChapter


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'type': 'email', 'placeholder': 'example@example.com'}))
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Имя"
        self.fields['contact_email'].label = ""
        self.fields['content'].label = "Сообщение"


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'type': 'email', 'placeholder': 'example@example.com'}))
    email.label = ""

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class AddBookForm(forms.Form):
    title = forms.CharField(required=True)
    author = forms.CharField(required=True)
    cover = forms.ImageField(required=False)
    isbn = forms.CharField(required=False)
    genre = forms.CharField(required=True)
    description = forms.CharField(required=True, widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(AddBookForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = "Название"
        self.fields['author'].label = "Автор (ФИ[О])"
        self.fields['description'].label = "Описание"
        self.fields['isbn'].label = "ISBN"
        self.fields['genre'].label = "Жанры"
        self.fields['cover'].label = ""


class AddChapterForm(forms.Form):
    title = forms.CharField(required=True)
    text = forms.CharField(required=True, widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(AddChapterForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = "Название"
        self.fields['text'].label = "Текст"

templates/add_book.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block meta-keywords %}<meta name="keywords" content="">{% endblock %}
{% block meta-description %}<meta name="description" content="">{% endblock %}
{% block meta-author %}<meta name="author" content="dalinar">{% endblock %}
{% block title %}Добавить книгу{% endblock %}
{% block content %}
    {% if error %}
        <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-lg-offset-2 col-lg-8 form-container">
            <ul>
                {{ error | safe }}
            </ul>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-lg-offset-2 col-lg-8 form-container">
            <form method="post" action="/book/add" enctype="multipart/form-data">
                {% for field in form %}
                    <div class="group">
                        {{ field }}
                        <label>{{ field.label }}</label>
                    </div>
                {% endfor %}
                <button type="submit" class="form-control">Отправить</button>
            </form>
        </div>
    </div>
    <br>
    <br>
    <br>
{% endblock %}

templates/add_chapter.html
{% extends 'base.html' %}
{% block meta-keywords %}<meta name="keywords" content="">{% endblock %}
{% block meta-description %}<meta name="description" content="">{% endblock %}
{% block meta-author %}<meta name="author" content="dalinar">{% endblock %}
{% block title %}Добавить главу{% endblock %}
{% block content %}
    {% if error %}
        <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-lg-offset-2 col-lg-8 form-container">
            <ul>
                {{ error | safe }}
            </ul>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-lg-offset-2 col-lg-8 form-container">
            <form method="post" action="{{ action_url }}">
                {% for field in form %}
                    <div class="group">
                        {{ field }}
                        <label>{{ field.label }}</label>
                    </div>
                {% endfor %}
                <button type="submit" class="form-control">Отправить</button>
            </form>
        </div>
    </div>
    <br>
    <br>
    <br>
{% endblock %}

templates/author.html
{% extends "base.html" %}
{% block title %}Все книги автора {{ author }}{% endblock %}
{% block content %}
    <p class="h2">Автор: <a href="{{ request.path }}">{{ author }}</a></p>
    {% if books %}
        <table class="books-table table table-hover table-striped">
            <thead>
                <tr>
                    <th class="hide-on-small-screen"></th>
                    <th>Книга</th>
                    <th>Жанры</th>
                    <th>Оценка</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                <tr>
                    <td class="hide-on-small-screen">{% if book.cover %}<p style="text-align: center;"><img src="{{ book.cover.url }}" alt="cover" style="max-height: 100px;"></p>{% endif %}</td>
                    <td><a data-toggle="tooltip" data-placement="bottom" title="{{ book.description }}" href="{{ book.get_absolute_url }}">{{ book }}</a></td>
                    <td>
                        {% for genre in book.genre.all %}
                            <a href="{{ genre.get_absolute_url }}">{{ genre }}</a>;
                        {% endfor %}
                    </td>
                    <td>{{ book.get_rating }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

{% block jquery %}
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock %}

templates/author_all.html
{% extends "base.html" %}
{% block title %}Все авторы{% endblock %}
{% block content %}
    <p class="h2">Все авторы</p>
    {% include "base/alphabet_anchor_links.html" %}
    {% if authors %}
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for author in authors %}
                {% ifchanged author.get_first_letter %}<tr><td><h4 id="{{ author.get_first_letter }}">{{ author.get_first_letter }}</h4></td></tr>{% endifchanged %}
                <tr>
                    <td><a href="{{ author.get_absolute_url }}">{{ author }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="initial-scale=1.0">
	<meta name="theme-color" content="rgba(60, 141, 188, 1)">
    {% block meta-keywords %}{% endblock %}
    {% block meta-description %}{% endblock %}
    {% block meta-author %}{% endblock %}
    {% include "base/js_include.html" %}
</head>
<body>
<div class="wrapper">
    {% include "base/header.html" %}
    {% include "account/login_modal.html" %}
    {% include "account/register_modal.html" %}
    {% include "base/sidebar.html" %}

    <!-- content wrapper -->
    <div class="container-fluid">
        {% include "base/breadcrumbs.html" %}
    	<div class="page-content">
            {% block content %}
            {% endblock %}
    	</div>
    </div><!-- end content wrapper -->

    {% include "base/footer.html" %}
</div>
</body>
{% block jquery %}
{% endblock %}
</html>

templates/book.html
{% extends 'base.html' %}
{% block meta-keywords %}<meta name="keywords" content="">{% endblock %}
{% block meta-description %}<meta name="description" content="">{% endblock %}
{% block meta-author %}<meta name="author" content="dalinar">{% endblock %}
{% block title %}book{% endblock %}
{% block content %}
    <p class="h2">{{ book }}</p>
    <div class="row">
        <div class="col-xs-4 col-md-3"><p style="text-align: center"><img src="{{ book.cover.url }}" alt="cover" style="height: auto; max-width: 100% !important; "></p></div>
        <div class="col-xs-8 col-md-9">
            <b>Автор: </b><a href="{{ book.author.get_absolute_url }}">{{ book.author }} </a><br>
            <b>Жанры: </b>{% for genre in book.genre.all %}<a href="{{ genre.get_absolute_url }}">{{ genre }}</a>; {% endfor %}<br>
            <b>Оценка: </b> {{ book.get_rating }} {% include 'upvote_downvote_links.html' %}<br>
            <b>Описание: </b> {{ book.description }}<br>
        </div>
    </div>
    {% if chapters %}
        <table class="chapters-table table table-hover table-striped">
            <thead>
                <tr>
                    <th>№</th>
                    <th>Название</th>
                    <th>Добавлено</th>
                    <th>Cкачать</th>
                    {% if user == book.uploaded_by_user %}<th>Действие</th>{% endif %}
                </tr>
            </thead>
            <tbody>
                {% for chapter in chapters %}
                <tr>
                    <td>{{ chapter.chapter_number }}</td>
                    <td><a href="{{ chapter.get_absolute_url }}">{{ chapter.title }}</a></td>
                    <td>{{ chapter.upload_date }}</td>
                    <td>txt fb2</td>
                    {% if user == book.uploaded_by_user %}<td><a href="{{ chapter.get_edit_url }}">Редактировать</a>{% endif %}
                </tr>
                {% endfor %}
                {% if user == book.uploaded_by_user %}
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><a href="{{ book.get_absolute_url }}/addchapter">Добавить</a></td>
                {% endif %}
            </tbody>
        </table>
    {% endif %}
    {% if chapters_null %}
        <p class="h4">{{ chapters_null }}. {% if user == book.uploaded_by_user %}<a href="{{ book.get_absolute_url }}/addchapter">Добавить?</a> {% endif %}</p>
    {% endif %}
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block title %}Обратная связь{% endblock %}
{% block content %}
<div class="row">
	<div class="col-xs-10 col-xs-offset-1 col-lg-offset-2 col-lg-8 form-container">
		<form method="post" action="/contact/">
            {% for field in form %}
                <div class="group">
                    {{ field }}
                    <label>{{ field.label }}</label>
                </div>
            {% endfor %}
			<button type="submit" class="form-control">Отправить</button>
		</form>
	</div>
</div>
{% endblock %}

templates/edit_chapter.html
{% extends 'base.html' %}
{% block meta-keywords %}<meta name="keywords" content="">{% endblock %}
{% block meta-description %}<meta name="description" content="">{% endblock %}
{% block meta-author %}<meta name="author" content="dalinar">{% endblock %}
{% block title %}Редактирование главы{% endblock %}
{% block content %}
    {% if error %}
        <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-lg-offset-2 col-lg-8 form-container">
            <ul>
                {{ error | safe }}
            </ul>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-lg-offset-2 col-lg-8 form-container">
            <form method="post" action="{{ action_url }}">
                    <div class="group">
                        <input type="text" name="title" required id="id_title" value="{{ title }}"/>
                        <label>Название</label>
                    </div>

                    <div class="group">
                        <textarea name="text" cols="40" rows="10" required id="id_text">{{ text }}</textarea>
                        <label>Текст</label>
                    </div>

                <button type="submit" class="form-control">Отправить</button>
            </form>
        </div>
    </div>
    <br>
    <br>
    <br>
{% endblock %}

templates/error.html
{% extends "base.html" %}
{% block title %}Ошибка{% endblock %}
{% block content %}
    <p class="h2">Ошибка</p>
    {% if error_text %}
        <p class="h4">{{ error_text }}</p>
    {% endif %}
    {% if form.errors %}
        {% for key,value in form.errors.items %}
            <p class="h4">{{ value|escape }}</p>
        {% endfor %}
    {% endif %}
{% endblock %}

templates/genre.html
{% extends "base.html" %}
{% block title %}Все книги жанра {{ genre }}{% endblock %}
{% block content %}
    <p class="h2">Жанр: <a href="{{ request.path }}">{{ genre }}</a></p>
    {% if books_not_found %}
        <p class="h4">{{ books_not_found }}</p>
    {% endif %}
    {% if books %}
        <table class="books-table table table-hover table-striped">
            <thead>
                <tr>
                    <th class="hide-on-small-screen"></th>
                    <th>Книга</th>
                    <th>Жанры</th>
                    <th>Оценка</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                <tr>
                    <td class="hide-on-small-screen">{% if book.cover %}<p style="text-align: center;"><img src="{{ book.cover.url }}" alt="cover" style="max-height: 100px;"></p>{% endif %}</td>
                    <td><a data-toggle="tooltip" data-placement="bottom" title="{{ book.description }}" href="{{ book.get_absolute_url }}">{{ book }}</a></td>
                    <td>
                        {% for genre in book.genre.all %}
                            <a href="{{ genre.get_absolute_url }}">{{ genre }}</a>;
                        {% endfor %}
                    </td>
                    <td>{{ book.get_rating }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

{% block jquery %}
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock %}

templates/genre_all.html
{% extends "base.html" %}
{% block title %}Все жанры{% endblock %}
{% block content %}
    <p class="h2">Все жанры</p>
    {% include "base/alphabet_anchor_links.html" %}
    {% if genres %}
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for genre in genres %}
                    {% ifchanged genre.get_first_letter %}<tr><td><h4 id="{{ genre.get_first_letter }}">{{ genre.get_first_letter }}</h4></td></tr>{% endifchanged %}
                    <tr>
                        <td><a href="{{ genre.get_absolute_url }}">{{ genre }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block meta-keywords %}<meta name="keywords" content="">{% endblock %}
{% block meta-description %}<meta name="description" content="">{% endblock %}
{% block meta-author %}<meta name="author" content="dalinar">{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <h2 style="text-align: center">Случайные книги</h2>
        </div>
    </div>
    <div class="row">
    {% for book in books %}
        <div class="col-md-4">
            <div class="row">
                <div class="col-xs-12">
                    <div class="h4" style="text-align: center;">{{ book }} </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-5 col-md-4"><p style="text-align: right"><img src="{{ book.cover.url }}" alt="cover" style="max-height: 150px; width: auto !important; "></p></div>
                <div class="col-xs-7 col-md-8">
                    <b>Автор: </b><a href="{{ book.author.get_absolute_url }}">{{ book.author }} </a><br>
                    <b>Жанры: </b>{% for genre in book.genre.all %}<a href="{{ genre.get_absolute_url }}">{{ genre }}</a>; {% endfor %}<br>
                    <b>Оценка: </b> {{ book.get_rating }} <br>
                    <a data-toggle="tooltip" data-placement="bottom" title="" href="#" data-original-title="{{ book.description }}">Описание</a><br>
                    <a href="{{ book.get_absolute_url }}">Читать</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    <br>
    <hr>
    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <h2 style="text-align: center">Последние добавленные книги</h2>
        </div>
    </div>
    <div class="row">
    {% for book in new_books %}
        <div class="col-md-4">
            <div class="row">
                <div class="col-xs-12">
                    <div class="h4" style="text-align: center;">{{ book }} </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-5 col-md-4"><p style="text-align: right"><img src="{{ book.cover.url }}" alt="cover" style="max-height: 150px; width: auto !important; "></p></div>
                <div class="col-xs-7 col-md-8">
                    <b>Автор: </b><a href="{{ book.author.get_absolute_url }}">{{ book.author }} </a><br>
                    <b>Жанры: </b>{% for genre in book.genre.all %}<a href="{{ genre.get_absolute_url }}">{{ genre }}</a>; {% endfor %}<br>
                    <b>Оценка: </b> {{ book.get_rating }} <br>
                    <a data-toggle="tooltip" data-placement="top" title="" href="#" data-original-title="{{ book.description }}">Описание</a><br>
                    <a href="{{ book.get_absolute_url }}">Читать</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

{% block jquery %}
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock %}

templates/upvote_downvote_links.html
{% if book %}
    {% if not user_has_voted %}
        ( Ваша оценка:
        {% for i in "12345" %}
            <a href="{{ book.get_absolute_url }}/vote/{{ i }}">{{ i }}</a>
        {% endfor %})
    {% endif %}
{% endif %}